### ISSUE TITLE
ministros de bolivia

### ISSUE THREAD

**Issue by 51114u9** [mauforonda/ministweets#1]
Según el anexo [Ministerios de Bolivia](https://es.wikipedia.org/wiki/Anexo:Ministerios_de_Bolivia) en la wikipedia hay 20 ministerios, revisando en twitter creo que solo falta por añadir:

* Ministerio de Trabajo, Empleo y Previsión Social, Oscar Mercado, https://twitter.com/totomercadocbba

Quizá corregir canciller por Ministerio de Relaciones Exteriores

**Comment by mauforonda** [comment]
Gracias por las ideas!

- He incluído al ministro: [commit](https://github.com/mauforonda/ministweets/commit/396834099123fad42307891baa45f57555d06f1b)
- Y he cambiado el título de la Canciller a Ministra de Relaciones Exteriores: [commit](https://github.com/mauforonda/ministweets/commit/d083545d8bd43142a57eef42c5d53f6dbb1109bc)
